repo_url: https://github.com/flanksource/canary-checker/
repo_name: Canary Checker
site_name: Canary Checker
theme:
  logo: ./images/cc-white.svg
  favicon: ./images/cc-blue.svg
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: indigo
    accent: light-blue
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: indigo
    accent: light-blue
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  features:
    - content.tabs.link
    - search.suggest
    - search.highlight
    # - navigation.instant
    # - navigation.sections
    # - navigation.tracking
    # - navigation.expand
    # - navigation.top
markdown_extensions:
  - admonition
  - fenced_code
  - pymdownx.smartsymbols
  - toc:
      permalink: False
      anchorlink: True
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed
  - codehilite:
      linenums: true
nav:
  - Introduction:
    - Overview:  ./index.md
  - Tutorials: 
    - Getting Started: ./getting-started.md
    - Contributing: ./dev-guide.md
  - Installation:
    - Install CLI: ./run.md
    - Install on Standalone Server: ./server.md
    - Install Kubernetes Operator: ./operator.md
  - Reference:
    - Checks:
      - Cloudwatch: ./check-types/cloudwatch.md
      - Containerd Pull: ./check-types/containerd-pull.md
      - Containerd Push: ./check-types/containerd-push.md
      - DNS: ./check-types/dns.md
      - Docker Pull: ./check-types/docker-pull.md
      - Docker Push: ./check-types/docker-push.md
      - EC2: ./check-types/ec2.md
      - Elasticsearch: ./check-types/elasticsearch.md
      - Exec: ./check-types/exec.md
      # - GCSBucket: ./check-types/gcs-bucket.md
      - GCS Database Backup: ./check-types/gcs-database-backup.md
      - Helm: ./check-types/helm.md
      - HTTP: ./check-types/http.md
      - ICMP: ./check-types/icmp.md
      - JMeter: ./check-types/jmeter.md
      - JUnit: ./check-types/junit.md
      - Kubernetes: ./check-types/kubernetes.md
      - LDAP: ./check-types/ldap.md
      - Mongo: ./check-types/mongo.md
      - MsSql: ./check-types/mssql.md
      - MySQL: ./check-types/mysql.md
      - Namespace: ./check-types/namespace.md
      - Pod: ./check-types/pod.md
      - Postgres: ./check-types/postgres.md
      - Prometheus: ./check-types/prometheus.md
      - Redis: ./check-types/redis.md
      - Restic: ./check-types/restic.md
      - S3 Bucket: ./check-types/s3-bucket.md
      - S3: ./check-types/s3.md
      - SMB / CIFS: ./check-types/smb.md
    - Topology:
      - Kubernetes Cluster: ./topology/kubernetes-cluster.md
      
